board/urls.py
from django.views.decorators.cache import cache_page
from django.urls import path
from .views import *

app_name = 'board'
urlpatterns = [
    path('', cache_page(5)(PostListView.as_view()), name='posts_view'),
    path('', PostsSort.as_view()),
    path('<int:pk>/', cache_page(1)(PostDetailView.as_view()), name='post'),
    path('add/', PostCreateView.as_view(), name='create_post'),
    path('<int:pk>/edit', PostUpdate.as_view(), name='update_post'),
    path('<int:pk>/del', PostDelete.as_view(), name='del_post'),
    path('comments', CommentsView.as_view(), name='comments'),
    path('<int:pk>/comment/', Comment.as_view(), name='comment'),
    path('comments/accept/<int:pk>', comment_accept),
    path('comments/delete/<int:pk>', comment_delete),
    path('user/', UpdateProfile.as_view(), name='profile_edit'),
    path('verify/', VerifyCodeView.as_view(), name='verify_page'),
    path('verify/', take_code, name='take_code'),
]

mmosite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('mmo/', include('board.urls')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),  # Для загрузки медиа через форму ckeditor
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.db.models import OneToOneField


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=128, verbose_name='Title')
    text = RichTextField()
    CATEGORY = (('tanks', 'Танки'),  # Категории, которые надо указать при публикации
                ('healers', 'Хилы'),
                ('damage_dealers', 'ДД'),
                ('dealers', 'Торговцы'),
                ('gild_masters', 'Гилдмастеры'),
                ('quest_givers', 'Квестгиверы'),
                ('blacksmiths', 'Кузнецы'),
                ('tanners', 'Кожевники'),
                ('potion_makers', 'Зельевары'),
                ('spell_masters', 'Мастера заклинаний'))
    category = models.CharField(max_length=24, choices=CATEGORY, verbose_name='Category')

    def __str__(self):
        return f'{self.user}, {self.title}, {self.category}, {self.dateCreation}'


class CommentPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField(verbose_name="Message")
    status = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username}, {self.text}, {self.dateCreation}, {self.status}'


# Костыль, чтобы сохранить код
class VerifyCode(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    code = models.IntegerField(default=0)

board/forms.py
from django.forms import ModelForm
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import *


# Создаём модельную форму
class CreatePostForm(ModelForm):
    text = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Post
        widgets = {'title': forms.TextInput(attrs={'size': '95'})}
        fields = ('category', 'title', 'text',)

    def __init__(self, *args, **kwargs):
        super(CreatePostForm, self).__init__(*args, **kwargs)
        self.fields['category'].label = "Category:"
        self.fields['title'].label = "Title"
        self.fields['text'].label = "If you need text...:"


class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentPost
        fields = ('text',)

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['text'].label = "Do you want comment?"


class CommentFilterForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        super(CommentFilterForm, self).__init__(*args, **kwargs)
        self.fields['title'] = forms.ModelChoiceField(
            label='Advert',
            queryset=Post.objects.filter(user=user).order_by('-dateCreation').values_list('title', flat=True),
            empty_label="All",
            required=False
        )


class EditProfile(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')


class AuthCodeForm(forms.Form):
    code = forms.IntegerField(label="Code")

board/views.py
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView, FormView
from django.views import View
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin  # Для ограничения доступа
from django.core.paginator import Paginator  # Для добавления страниц
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
import random

from .tasks import *
from .forms import *
from .models import *

DEFAULT_FROM_EMAIL = settings.DEFAULT_FROM_EMAIL


class PostListView(ListView):
    model = Post
    template_name = 'post_list.html'
    context_object_name = 'post_list'
    ordering = ['-dateCreation']
    paginate_by = 10


class PostsSort(View):
    # Сортировка и вывод страниц
    def get(self, request):
        posts = Post.objects.order_by('-dateCreation')
        p_paginator = Paginator(posts, 1)
        posts = p_paginator.get_page(request.GET.get('page', 1))

        data = {
            'posts': posts,
        }

        return render(request, 'post_list.html', data)


class PostDetailView(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if CommentPost.objects.filter(user=self.request.user).filter(post_id=self.kwargs.get('pk')):
            context['is_comment'] = "y"
        elif self.request.user == Post.objects.get(pk=self.kwargs.get('pk')).user:
            context['is_comment'] = "My"
        return context


class PostCreateView(RichTextField, CreateView):
    template_name = 'add_post.html'
    form_class = CreatePostForm
    permission_required = 'board.create_post'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.user = User.objects.get(id=self.request.user.id)
        post.save()
        return redirect(f'../{post.id}')


class PostUpdate(RichTextField, UpdateView):
    template_name = 'add_post.html'
    form_class = CreatePostForm
    permission_required = 'board.change_post'

    def get_object(self, **kwargs):
        id_post = self.kwargs.get('pk')
        return Post.objects.get(pk=id_post)

    def form_valid(self, form):
        post = form.save(commit=False)
        if post.user == User.objects.get(id=self.request.user.id):
            post.save()
            return redirect(f'../{post.id}')


class PostDelete(RichTextField, DeleteView):
    template_name = 'del_post.html'
    queryset = Post.objects.all()
    success_url = '/mmo'
    permission_required = 'board.delete_post'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user == Post.objects.get(pk=self.kwargs.get('pk')).user:
            return super().dispatch(request, *args, **kwargs)
        else:
            return HttpResponse("No")


class CommentsView(ListView):
    model = CommentPost
    template_name = 'comments.html'
    context_object_name = 'comments'

    title = str('')  # Переменная-костыль, так как гет контекст не хочет работать с локальной переменной

    def get_context_data(self, **kwargs):
        context = super(CommentsView, self).get_context_data(**kwargs)
        # Фильтр по айди
        if self.kwargs.get('pk') and Post.objects.filter(id=self.kwargs.get('pk')).exists():
            self.title = str(Post.objects.get(id=self.kwargs.get('pk')).title)
            print(self.title)
        context['form'] = CommentFilterForm(self.request.user, initial={'title': self.title})
        context['title'] = self.title
        if self.title:
            post = Post.objects.get(title=self.title)
            context['filter_comments'] = CommentPost.objects.filter(post=post).order_by('-dateCreation')
        else:
            context['filter_comments'] = CommentPost.objects.filter(post__user=self.request.user).order_by(
                '-dateCreation')
        context['mycomments'] = CommentPost.objects.filter(user=self.request.user).order_by('-dateCreation')
        return context

    def post(self, request, *args, **kwargs):
        self.title = self.request.POST.get('title')
        if self.kwargs.get('pk'):
            return HttpResponseRedirect('/comments')
        return self.get(request, *args, **kwargs)


@login_required
def comment_accept(request, **kwargs):
    if request.user.is_authenticated:
        comment_post = CommentPost.objects.get(id=kwargs.get('pk'))
        comment_post.status = True
        comment_post.save()
        comment_accept_send_email.delay(comment_id=comment_post.id)
        return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/accounts/login')


@login_required
def comment_delete(request, **kwargs):
    if request.user.is_authenticated:
        comment_post = CommentPost.objects.get(id=kwargs.get('pk'))
        comment_post.delete()
        return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/accounts/login')


class Comment(RichTextField, CreateView):
    model = CommentPost
    template_name = 'comment.html'
    form_class = CommentForm
    permission_required = 'board.create_comment'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        comment_post = form.save(commit=False)
        comment_post.user = User.objects.get(id=self.request.user.id)
        comment_post.post = Post.objects.get(id=self.kwargs.get('pk'))
        comment_post.save()
        # print(comment_post)
        comment_send_email.delay(comment_id=comment_post.id)
        # print(1, comment_send_email)
        return redirect(f'/mmo/{self.kwargs.get("pk")}')


class UpdateProfile(LoginRequiredMixin, UpdateView):
    model = User
    form_class = EditProfile
    success_url = 'profile'
    template_name = 'update_profile.html'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.id
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.groups.filter(name='activated').exists():
            context['is_verify'] = False
        else:
            context['is_verify'] = True
        return context


@login_required
def take_code(request):
    # Код временно сохраняется в базу данных
    if not request.user.groups.filter(name='activated').exists():
        code = random.randint(1000, 9999)
        VerifyCode.objects.create(user=request.user, code=code)

        email_subject = f'MMO: verify e-mail',
        user_emails = [request.user.email, ],

        msg = EmailMultiAlternatives(
            subject=email_subject,
            body=f'Greetings, {request.user.username}! Your verify code {code}'
                 f'Confirm your email \nhttp://127.0.0.1:8000/user/verify',
            from_email=settings.DEFAULT_FROM_EMAIL,
            to=user_emails
        )

        msg.send()
        return redirect(f'/mmo/verify')


class VerifyCodeView(FormView):
    model = VerifyCode
    form_class = AuthCodeForm
    template_name = 'profile_code.html'

    def form_valid(self, form, **kwargs):
        code_user = VerifyCode.objects.get(user=self.request.user)
        if form.cleaned_data['code'] == code_user.code:
            Group.objects.get(name='Activated').user_set.add(self.request.user)
            # И удаляем из базы данных
            VerifyCode.objects.filter(user=self.request.user).delete()
            return redirect(f'/mmo/user')

board/templates/add_post.html
{% extends 'default.html' %}
{% load bootstrap4 %}


{% block title %}
Add New Advert
{% endblock title %}

{% block content %}
    <br>
    <h3>Add New Advert</h3><br>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
		<input class="btn btn-info" type="submit" value="Сохранить">
	</form><br>
    <input type=button value="Назад" class="btn btn-secondary" onClick="javascript:history.go(-1);">
{% endblock content %}

board/templates/comment.html
{% extends 'default.html' %}
{% load bootstrap4 %}
{% block title %}Comment{% endblock title %}
{% load static %}

{% block content %}
    <br>
    <h3>Comment:</h3><br>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% bootstrap_form form layout='horizontal' %}
		<input class="btn btn-info" type="submit" value="Save">
	</form><br>
    <input type=button value="Back" class="btn btn-secondary" onClick="javascript:history.go(-1);">
{% endblock content %}

board/templates/comments.html
{% extends 'default.html' %}
{% load bootstrap4 %}
{% block title %}Comments{% endblock title %}

{% block content %}
<br>
<h1>Comments for my Adverts:</h1><br>
	<form method="POST">
		{% csrf_token %}
        {{ form }}
		<input class="btn btn-info" type="submit" value="Show">
	</form><br>
    {% if title %}
        <h3>Comment</h3>
        {% if filter_commemts %}
            {% for comment in filter_commetns %}
                <b>Comment: </b>{{ comment.text }}<br>
                <span><p>User: {{ comment.user.username }} |
                    Date: {{ comment.dateCreation|date:'d.M.Y' }} г.</p></span><br>
                    {% if comment.status == False %}
                        <a href="comments/accept/{{ comment.id }}"><p>Accept</p></a>
                        <a href="comments/delete/{{ comment.id }}"><p>Nonono</p></a>
                    {% else %}
                        <p>It's yours</p>
                    {% endif %}
                <br><br>
            {% endfor %}
        {% else %}
            <br>
            <h5>Nothing</h5>
        {% endif %}
    {% else %}
        <h3>All Adverts' comment</h3>
        {% if filter_comments %}
            {% for comment in filter_comments %}
                <br>
                <p>Advert: <a href="{{ comment.post_id }}">{{ comment.post.title }}</a></p><br>
                <p>Comment: {{ comment.text|truncatechars:50|safe }}</p><br>
                <span>From user: {{ comment.user.username }} ||
                    Date Comment: {{ comment.dateCreation|date:'d.M.Y' }} г.</span><br><br>
                    {% if comment.status == False %}
                        <a href="comments/accept/{{ comment.id }}">Accept</a>
                        <br>
                        <a href="comments/delete/{{ comment.id }}">Nonono</a>
                {% else %}
                    <p>Accepted</p>
                {% endif %}
                <br><hr><br>
            {% endfor %}
        {% else %}
            <h5>Откликов нет!</h5>
        {% endif %}
    {% endif %}
    <br><br>
    <h3>My Comments</h3>
    {% if mycomments %}
        {% for comment in mycomments %}
            <p>Advert:</p>
            <a href="{{ comment.post_id }}">{{ comment.post.title }}</a><br>
            <p>Advert's Author:  {{ comment.post.user.username }} |
                Advert's Date: {{ comment.post.dateCreation|date:'d.M.Y' }}</p><br>
            <p>My Comment:</p>
            {{ comment.text }}<br>
            <span>Date Comment: {{ comment.dateCreation|date:'d.M.Y' }}</span><br>
            {% if comment.status == True %}
                <p>You're in!</p>
            {% else %}
                <p>You are not in</p>
            {% endif %}
        <br><br>
        {% endfor %}
    {% else %}
        <h5>No Comments!</h5>
    {% endif %}
{% endblock content %}

board/templates/del_post.html
{% extends 'default.html' %}

{% block title %}
Delete Post
{% endblock title %}

{% block content %}
<br>
<h3>Delete this post?</h3>
<div class="card">
    <div class="card-header">
        <h3>
            {{ post.title }}
        </h3>
        <div>
            Автор: {{ post.user }}
        </div>
    </div>
    <div class="card-body">
        {{ post.text|truncatechars:20|safe }}
    </div>
</div>
<br>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <input class="btn btn-info btn-gradient" type="submit" value="Delete">
    </form>
</div>
<br>
<br>
{% endblock content %}

board/templates/post.html
{% extends 'default.html' %}
{% load bootstrap4 %}

{% block title %}
Advert
{% endblock title %}

{% block content %}

{% if post %}
<div class="card" xmlns="http://www.w3.org/1999/html">
    <div class="card-header">
        <h3>{{ post.title }}</h3>
        <div>
            Автор: {{ post.user }}
        </div>
        <div>
            <span>{{ post.dateCreate|date:'d m y, H:i' }}</span>
        </div>
        <div>
            <span class="badge bg-info"> {{ post.get_category_display }}</span>
        </div>
    </div>
    <div class="card-body">
        <span>{{ post.text|safe }}</span>
    </div>
    {% if request.user == post.user %}
    <div class="container">
        <span><a href="{% url 'board:update_post' post.id %}">Update</a></span>
        <span><a href="{% url 'board:del_post' post.id %}">Delete</a></span>
        <br>
        <br>
    </div>
    {% endif %}
</div>
    {% if user.is_authenticated %}
        <br><br>
<!--        Если пост откомментирован, если это свой пост и если не откомментирован-->
        {% if is_comment == "y" %}
            <p>You commented this post</p><br>
            <a href="{% url 'board:comments' %}">Your comments</a>
        {% elif is_comment == "My" %}
            <a href="{% url 'board:comments' %}">Look all answers</a> <br>
        {% else %}
            <a href="comment/"><button class="btn btn-info"> Add Comment</button></a>
        {% endif %}
    {% endif %}
    <br><br>
{% else %}
    <h3>Страница не существует</h3>
{% endif %}

<br><br>

{% endblock content %}

board/templates/post_list.html
{% extends 'default.html' %}
{% load bootstrap4 %}

{% block title %}
Adverts
{% endblock title %}

{% block content %}
<h1>Adverts</h1>

<hr> <br>
{% if user.is_authenticated %}
<div class="container ml-3">
<a href="add">
    <button class="btn btn-info btn-gradient">New Advert</button>
</a>
</div>
{% endif %}
<br>
{% if post_list %}
<div class="grid-posts mb-10">
    <div class="container">
        <div class="row">
            {% for post in post_list %}
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <p class="badge bg-info">{{ post.get_category_display }}</p> ||
                            {{ post.title }}
                            <p class="text-end">{{ post.user }} || {{ post.dateCreation|date:'d m y' }}</p>
                        </div>
                        <div class="card-body">
                            <div class="container">
                                {{ post.text|truncatechars:50|safe }}
                                {% if user.is_authenticated %}
                                <p class="text-end"><a href="{{ post.id }}">Open</a></p>
                                {% else %}
                                <p class="text-end text-muted">Login for watch detail...</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <br>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% else %}
    <h3>Статей нет</h3>
{% endif %}

{% include 'parts/paginator.html' %}

<br> <br>
{% endblock content %}

board/templates/profile_code.html
{% extends 'default.html' %}
{% load bootstrap4 %}
{% block title %}Profile{% endblock %}


{% block content %}

    <br><br>
    <h3>Your Profile: </h3>
    <br>
    <h5>User name: {{user.username}}</h5>
    <h5>E-mail: {{user.email}}</h5>

    <br><br>
    <a class="btn btn-secondary" href="{% url 'account_logout' %}" role="button">Выйти из аккаунта</a>

    <br><br><br>
    {% if not verify %}
        <h5>Enter your verify code </h5><br>
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <input class="btn btn-info" type="submit" value="Check">
        </form>
    {% else %}
        <p>Your email is checked</p>
    {% endif %}
{% endblock %}

board/templates/update_profile.html
{% extends 'default.html' %}
{% load bootstrap4 %}
{% block title %}Profile update{% endblock %}
{% block content %}

<br><br>
<h2>Profile update</h2><br>

<form method="post">
	{% csrf_token %}
	{% bootstrap_form form layout='horizontal' %}
	{% buttons submit='Save' %}{% endbuttons %}
</form>
{% if is_verify %}
<p>Enter your email. We'll send you verify code</p>
<a class="btn btn-secondary" href="{% url 'board:take_code' %}" role="button">Take Code</a>
<br>
<br>
{% endif %}
<a class="btn btn-secondary" href="{% url 'account_logout' %}" role="button">Logout</a>

{% endblock content %}