board/urls.py
from django.views.decorators.cache import cache_page
from django.urls import path
from .views import *

app_name = 'board'
urlpatterns = [
    path('', cache_page(5)(PostListView.as_view()), name='posts_view'),
    path('', PostsSort.as_view()),
    path('<int:pk>/', cache_page(1)(PostDetailView.as_view()), name='post'),
    path('add/', PostCreateView.as_view(), name='create_post'),
    path('<int:pk>/edit', PostUpdate.as_view(), name='update_post'),
    path('<int:pk>/del', PostDelete.as_view(), name='del_post'),
    path('comments', CommentsView.as_view(), name='comments'),
    path('<int:pk>/comment/', Comment.as_view(), name='comment'),
    path('comments/accept/<int:pk>', comment_accept),
    path('comments/delete/<int:pk>', comment_delete),
    path('user/', UpdateProfile.as_view(), name='profile_edit'),
    path('verify/', VerifyCodeView.as_view(), name='verify_page'),
    path('verify/', take_code, name='take_code'),
]

mmosite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('mmo/', include('board.urls')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),  # Для загрузки медиа через форму ckeditor
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/parts/footer.html
<footer class="footer mt-auto py-3 bg-light">
    {% load cache %}
<!--    {% cache 120 footer %}-->
    <div class="container">
        <span class="text-muted">Footer</span>
        <span class="text-muted text-center">Copyright</span>
        <span class="text-muted text-end">Something else</span>
    </div>
<!--    {% endcache %}-->
</footer>

templates/parts/header.html
{% load static %}
<header class="p-3 text-bg-dark">
    {% load cache %}   <!-- Кэширование -->
    {% cache 60 header %}
    {% block header %}
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'icons/logo.svg' %}" alt="logo" width="33" height="33">
            </a>

       <ul class="btn-group btn-group-toggle nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0" data-toggle="buttons">
           <li>
               <a href="/" class="nav-link px-2 text-info">
                    <button class="btn btn-outline-info">
                        Home
                    </button>
               </a>
           </li>
           <li>
               <a href="{% url 'board:posts_view' %}" class="nav-link px-2 text-info">
                   <button class="btn btn-outline-info">
                       Adverts
                   </button>
               </a>
           </li>
           <li>
               <a href="/" class="nav-link px-2 text-info">
                    <button class="btn btn-outline-info">
                        None
                    </button>
               </a>
           </li>
        </ul>
       {% endblock header %}
       {% endcache %}

       {% if request.user.username %}
<!--     Если пользователь авторизован, показывается имя и кнопка выхода-->
            <div class="text-end">
                <a href="{% url 'board:comments' %}"><button class="btn btn-outline-info">Comments</button></a>
                <a href="{% url 'board:profile_edit' %}"><button class="btn btn-outline-info">{{request.user.username}}</button></a>
                <a href="{% url 'account_logout' %}"><button type="button" class="btn btn-light">Logout</button></a>
            </div>
            {% else %}
<!--     Если не авторизован, предлагает авторизацию-->
            <div class="text-end">
                <a href="{% url 'account_signup' %}"><button type="button" class="btn btn-light">Registration</button></a>
                <a href="{% url 'account_login' %}"><button type="button" class="btn btn-outline-info">Login</button></a>
            </div>
       {% endif %}
   </div>
 </div>
</header>